version: "3.0"

services:
  fmotor_android_compiler:
    image: kivy/buildozer
    container_name: fmotor_android_compiler
    volumes:
      - ./src:/home/user/hostcwd
    command: android debug deploy run
